app = "office-timesheet-db"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "pg_data"
  destination = "/var/lib/postgresql/data"

[[services]]
  internal_port = 5432
  protocol = "tcp"

[env]
  POSTGRES_DB = "office_timesheet"
  POSTGRES_USER = "postgres"
  PGDATA = "/var/lib/postgresql/data/pgdata"
